add_executable(test_co_core test_co_core.c)
target_link_libraries(test_co_core PRIVATE canopen_core)
if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(test_co_core PRIVATE -Wall -Wextra -Wpedantic -Werror)
elseif(MSVC)
    target_compile_options(test_co_core PRIVATE /W4 /WX)
endif()
foreach(test_name frame init tx routing)
    add_test(NAME core_${test_name} COMMAND test_co_core ${test_name})
endforeach()

add_executable(test_co_od test_co_od.c)
target_link_libraries(test_co_od PRIVATE canopen_core)
if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(test_co_od PRIVATE -Wall -Wextra -Wpedantic -Werror)
elseif(MSVC)
    target_compile_options(test_co_od PRIVATE /W4 /WX)
endif()
foreach(test_name find read write definition)
    add_test(NAME od_${test_name} COMMAND test_co_od ${test_name})
endforeach()

add_executable(test_co_device_od test_co_device_od.c)
target_link_libraries(test_co_device_od PRIVATE canopen_core)
if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(test_co_device_od PRIVATE -Wall -Wextra -Wpedantic -Werror)
elseif(MSVC)
    target_compile_options(test_co_device_od PRIVATE /W4 /WX)
endif()
add_test(NAME od_device COMMAND test_co_device_od)
add_test(NAME od_signed COMMAND test_co_device_od signed)
add_executable(test_co_nmt test_co_nmt.c)
target_link_libraries(test_co_nmt PRIVATE canopen_core)
if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(test_co_nmt PRIVATE -Wall -Wextra -Wpedantic -Werror)
elseif(MSVC)
    target_compile_options(test_co_nmt PRIVATE /W4 /WX)
endif()
add_test(NAME nmt COMMAND test_co_nmt)

add_executable(test_co_hb test_co_hb.c)
target_link_libraries(test_co_hb PRIVATE canopen_core)
if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(test_co_hb PRIVATE -Wall -Wextra -Wpedantic -Werror)
elseif(MSVC)
    target_compile_options(test_co_hb PRIVATE /W4 /WX)
endif()
add_test(NAME heartbeat COMMAND test_co_hb)

add_executable(test_co_sdo test_co_sdo.c)
target_link_libraries(test_co_sdo PRIVATE canopen_core)
if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(test_co_sdo PRIVATE -Wall -Wextra -Wpedantic -Werror)
elseif(MSVC)
    target_compile_options(test_co_sdo PRIVATE /W4 /WX)
endif()
add_test(NAME sdo COMMAND test_co_sdo)
find_package(Python3 REQUIRED COMPONENTS Interpreter)
add_test(NAME od_eds COMMAND ${Python3_EXECUTABLE}
    ${CMAKE_CURRENT_SOURCE_DIR}/test_eds.py
    $<TARGET_FILE:test_co_device_od>
    ${PROJECT_SOURCE_DIR}/eds/CANopen_IO_Node.eds)
